
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: setup environment
          command: |
            make dev
            make info
            uname -a
            lsb_release -a
      - run:
          name: build and test
          command: make ci
