
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: make dev
      - make info
      - uname -a
      - lsb_release -a
      - make ci
